### ISSUE TITLE
Please enable gzip response

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/Workspace#31]
Looks like gzipping is not turned on.  Can we enable it?   My ~1.5mb model would be <200 kb.   

```
visitor099-107:~ nc$ ls -lh test.json 
-rw-r--r--  1 nc  staff   1.4M Jun 22 16:07 test.json
visitor099-107:~ nc$ gzip test.json 
visitor099-107:~ nc$ ls -lh test.json.gz 
-rw-r--r--  1 nc  staff   131K Jun 22 16:07 test.json.gz
```

**Comment by olsonanl** [comment]
We'll have to check this again; Dan enabled a setting on the proxy that was supposed to have done this but apparently it is not working as expected.

________________________________

**Comment by danielolson5** [comment]
I've verified compression is enabled on p3.theseed.org at http://www.whatsmyip.org/http-compression-test/
Neal, afaik there's no good way to validate it with files like you're doing - it happens within the protocol stream and the client needs to request it, most browsers do request it.  If you use a client with compression enabled - it's going to decompress it and emit uncompressed content.

**Comment by nconrad** [comment]
There's a few reason I think it may not be enabled on the workspace serverice or it's not working for whatever reason.

1) There is no "content-encoding: gzip" in the response header.  Supposedly this should be there and I see it's there for other resources like google-analytics.  I also referred to https://msdn.microsoft.com/en-us/library/aa287673(v=vs.71).aspx and https://en.wikipedia.org/wiki/HTTP_compression

![screen shot 2015-06-24 at 3 02 33 pm](https://cloud.githubusercontent.com/assets/1194246/8340644/68c7324e-1a85-11e5-96f7-c893c367f700.png)

![screen shot 2015-06-24 at 3 03 26 pm](https://cloud.githubusercontent.com/assets/1194246/8340665/889148c6-1a85-11e5-95bf-73e4bcb9916d.png)

2) The size and content size for my large files in google dev tools are the same.   Usually these are different when gzip is used.

![screen shot 2015-06-24 at 3 02 48 pm](https://cloud.githubusercontent.com/assets/1194246/8340673/9dd4593a-1a85-11e5-8f02-02a7ab8023e3.png)

3) This fails: http://www.whatsmyip.org/http-compression-test/?url=aHR0cDovL3AzLnRoZXNlZWQub3JnL3NlcnZpY2VzL1dvcmtzcGFjZQ==   

But this doesn't fail:  http://www.whatsmyip.org/http-compression-test/?url=aHR0cDovL3AzLnRoZXNlZWQub3Jn

And, this supports my theory when I looked for "content-encoding: gzip" in the response headers.

![screen shot 2015-06-24 at 3 14 42 pm](https://cloud.githubusercontent.com/assets/1194246/8340713/d0b245e2-1a85-11e5-8e23-e043c4f0848e.png)

**Comment by nconrad** [comment]
Any updates on this?

**Comment by danielolson5** [comment]
Can you retest this?  The root of the url will not compress because for some reason nginx isn't compressing error messages.

**Comment by olsonanl** [comment]
Neal, if you can give us a specific POST that is not compressing properly we'll be able to chase this better as well.

**Comment by olsonanl** [comment]
$ curl -o foo -H "Accept-Encoding: gzip" -D - -X POST --data-binary '{"id": 1, "params":[], "method": "Workspace.version"}' https://p3.theseed.org/services/Workspace
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0HTTP/1.1 200 OK
Server: nginx/1.7.6
Date: Thu, 09 Jul 2015 14:57:26 GMT
Content-Type: application/json
Connection: close
Vary: Accept-Encoding
Content-Encoding: gzip

curl: (56) SSLRead() return error -9806

$ gunzip < foo
{"error":null,"id":1,"result":["0.1.0"]}

**Comment by danielolson5** [comment]
Neal and I syncd up on this today, and it appears to be compressing properly now.  Closing this out.

**Comment by olsonanl** [comment]
What was the problem?

On Jul 9, 2015, at 1:36 PM, Daniel Olson <notifications@github.com<mailto:notifications@github.com>> wrote:


Neal and I syncd up on this today, and it appears to be compressing properly now. Closing this out.

**Comment by nconrad** [comment]
Thank you so much!  I'm not sure what the issue was, but it looks like loading the same Ecoli model is ~2 - 3 times faster, measured from the same network (see below).  We may want to do some benchmarking and set some thresholds someday.  Also could consider storing data gzipped. 

<img width="1292" alt="screen shot 2015-07-09 at 7 17 27 pm" src="https://cloud.githubusercontent.com/assets/1194246/8610062/ce12c2be-2672-11e5-9ba8-52a1c11cb787.png">

Now, who has an intern to make REST APIs for this stuff?  :)  ...I can never find the time.  This is a pratical example where caching and debugging would have been easier
