### ISSUE TITLE
update_metadata doesn't work?

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/Workspace#32]
I get the following when trying to update metadata on objects. 

Request:

{"version":"1.1","method":"Workspace.update_metadata","id":"8127539027482271","params":[{"objects":["/nconrad@patricbrc.org/home/test46.fa",{"test":"blah blah"}]}]}:

Response:

{"version":"1.1","error":{"error":"Can't use string (\"/nconrad@patricbrc.org/home/test\"...) as an ARRAY ref while \"strict refs\" in use at /disks/p3/deployment/lib/Bio/P3/Workspace/WorkspaceImpl.pm line 1638.\n","name":"JSONRPCError","code":-32603,"message":"Can't use string (\"/nconrad@patricbrc.org/home/test\"...) as an ARRAY ref while \"strict refs\" in use"},"id":"8127539027482271"}

**Comment by olsonanl** [comment]
The objects value is a list of lists; the internal list is the [path, metadata, type, timestamp] tuple. 

You're missing a wrapping list.

**Comment by nconrad** [comment]
doh.  Thanks!
