### ISSUE TITLE
meaningful error messages

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/Workspace#4]
Noting that error messages could be improved.  When I tried to delete brettin's workspace, I got this:

{"version":"1.1","error":{"error":"_ERROR_Workspace not found!_ERROR_\n\nTrace begun at /disks/p3/deployment/lib/Bio/P3/Workspace/WorkspaceImpl.pm line 114\nBio::P3::Workspace::WorkspaceImpl::_error('Bio::P3::Workspace::WorkspaceImpl=HASH(0x4721408)', 'Workspace not found!') called at /disks/p3/deployment/lib/Bio/P3/Workspace/WorkspaceImpl.pm line 163\nBio::P3::Workspace::WorkspaceImpl::_get_db_ws('Bio::P3::Workspace::WorkspaceImpl=HASH(0x4721408)', 'HASH(0x4a8a590)') called at /disks/p3/deployment/lib/Bio/P3/Workspace/WorkspaceImpl.pm line 2899\nBio::P3::Workspace::WorkspaceImpl::delete_workspace('Bio::P3::Workspace::WorkspaceImpl=HASH(0x4721408)', 'HASH(0x4a8a0e0)') called at /disks/p3/deployment/lib/Bio/P3/Workspace/Service.pm line 361\neval {...} at /disks/p3/deployment/lib/Bio/P3/Workspace/Service.pm line 353\nBio::P3::Workspace::Service::call_method('Bio::P3::Workspace::Service=HASH(0x40a6b38)', 'HASH(0x4aa9640)', 'HASH(0x4a89d98)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/RPC/Any/Server.pm line 34\neval {...} at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/RPC/Any/Server.pm line 27\nRPC::Any::Server::handle_input('Bio::P3::Workspace::Service=HASH(0x40a6b38)', 'HASH(0x4aa9a78)') called at /disks/p3/deployment/lib/Workspace.psgi line 20\nPlack::Sandbox::_2fdisks_2fp3_2fdeployment_2flib_2fWorkspace_2epsgi::__ANON__('HASH(0x4aa9a78)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Plack/Middleware/CrossOrigin.pm line 176\nPlack::Middleware::CrossOrigin::call('Plack::Middleware::CrossOrigin=HASH(0x47231d0)', 'HASH(0x4aa9a78)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Plack/Component.pm line 50\nPlack::Component::__ANON__('HASH(0x4aa9a78)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Plack/Middleware/AccessLog.pm line 24\nPlack::Middleware::AccessLog::call('Plack::Middleware::AccessLog=HASH(0x1b79588)', 'HASH(0x4aa9a78)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Plack/Component.pm line 50\nPlack::Component::__ANON__('HASH(0x4aa9a78)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Plack/Util.pm line 142\neval {...} at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Plack/Util.pm line 142\nPlack::Util::run_app('CODE(0x1b93bb8)', 'HASH(0x4aa9a78)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Starman/Server.pm line 281\nStarman::Server::process_request('Starman::Server=HASH(0x17ec430)', 'Net::Server::Proto::TCP=GLOB(0x4aa29e8)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Net/Server.pm line 74\nNet::Server::run_client_connection('Starman::Server=HASH(0x17ec430)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Net/Server/PreFork.pm line 229\neval {...} at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Net/Server/PreFork.pm line 229\nNet::Server::PreFork::run_child('Starman::Server=HASH(0x17ec430)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Net/Server/PreFork.pm line 187\nNet::Server::PreFork::run_n_children('Starman::Server=HASH(0x17ec430)', 5) called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Net/Server/PreFork.pm line 111\nNet::Server::PreFork::loop('Starman::Server=HASH(0x17ec430)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Net/Server.pm line 60\nNet::Server::run('Starman::Server=HASH(0x17ec430)', 'port', 'ARRAY(0x1b386c8)', 'host', '*', 'proto', 'tcp', 'serialize', 'none', 'min_servers', 5, 'min_spare_servers', 4, 'max_spare_servers', 4, 'max_servers', 5, 'max_requests', 1000, 'user', 30220, 'group', '30220 30220 45056', 'listen', 1024, 'check_for_waiting', 1, 'no_client_stdout', 1, 'pid_file', '/disks/p3/deployment/services/Workspace/service.pid', 'setsid', 1, 'background', 1, 'log_file', '/disks/p3/deployment/services/Workspace/error.log') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Starman/Server.pm line 89\nStarman::Server::run('Starman::Server=HASH(0x17ec430)', 'CODE(0x17ec310)', 'HASH(0x17ec028)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Plack/Handler/Starman.pm line 18\nPlack::Handler::Starman::run('Plack::Handler::Starman=HASH(0x17ec3d0)', 'CODE(0x17ec310)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Plack/Loader/Delayed.pm line 20\nPlack::Loader::Delayed::run('Plack::Loader::Delayed=HASH(0x1593dd8)', 'Plack::Handler::Starman=HASH(0x17ec3d0)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Plack/Runner.pm line 277\nPlack::Runner::run('Plack::Runner=HASH(0x15d9b68)') called at /disks/p3/runtime/bin/starman line 38\n","name":"JSONRPCError","code":-32603,"message":"_ERROR_Workspace not found!_ERROR_\n\nTrace begun at /disks/p3/deployment/lib/Bio/P3/Workspace/WorkspaceImpl.pm line 114\nBio::P3::Workspace::WorkspaceImpl::_error('Bio::P3::Workspace::WorkspaceImpl=HASH(0x4721408)', 'Workspace not found!') called at /disks/p3/deployment/lib/Bio/P3/Workspace/WorkspaceImpl.pm line 163\nBio::P3::Workspace::WorkspaceImpl::_get_db_ws('Bio::P3::Workspace::WorkspaceImpl=HASH(0x4721408)', 'HASH(0x4a8a590)') called at /disks/p3/deployment/lib/Bio/P3/Workspace/WorkspaceImpl.pm line 2899\nBio::P3::Workspace::WorkspaceImpl::delete_workspace('Bio::P3::Workspace::WorkspaceImpl=HASH(0x4721408)', 'HASH(0x4a8a0e0)') called at /disks/p3/deployment/lib/Bio/P3/Workspace/Service.pm line 361\neval {...} at /disks/p3/deployment/lib/Bio/P3/Workspace/Service.pm line 353\nBio::P3::Workspace::Service::call_method('Bio::P3::Workspace::Service=HASH(0x40a6b38)', 'HASH(0x4aa9640)', 'HASH(0x4a89d98)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/RPC/Any/Server.pm line 34\neval {...} at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/RPC/Any/Server.pm line 27\nRPC::Any::Server::handle_input('Bio::P3::Workspace::Service=HASH(0x40a6b38)', 'HASH(0x4aa9a78)') called at /disks/p3/deployment/lib/Workspace.psgi line 20\nPlack::Sandbox::_2fdisks_2fp3_2fdeployment_2flib_2fWorkspace_2epsgi::__ANON__('HASH(0x4aa9a78)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Plack/Middleware/CrossOrigin.pm line 176\nPlack::Middleware::CrossOrigin::call('Plack::Middleware::CrossOrigin=HASH(0x47231d0)', 'HASH(0x4aa9a78)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Plack/Component.pm line 50\nPlack::Component::__ANON__('HASH(0x4aa9a78)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Plack/Middleware/AccessLog.pm line 24\nPlack::Middleware::AccessLog::call('Plack::Middleware::AccessLog=HASH(0x1b79588)', 'HASH(0x4aa9a78)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Plack/Component.pm line 50\nPlack::Component::__ANON__('HASH(0x4aa9a78)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Plack/Util.pm line 142\neval {...} at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Plack/Util.pm line 142\nPlack::Util::run_app('CODE(0x1b93bb8)', 'HASH(0x4aa9a78)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Starman/Server.pm line 281\nStarman::Server::process_request('Starman::Server=HASH(0x17ec430)', 'Net::Server::Proto::TCP=GLOB(0x4aa29e8)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Net/Server.pm line 74\nNet::Server::run_client_connection('Starman::Server=HASH(0x17ec430)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Net/Server/PreFork.pm line 229\neval {...} at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Net/Server/PreFork.pm line 229\nNet::Server::PreFork::run_child('Starman::Server=HASH(0x17ec430)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Net/Server/PreFork.pm line 187\nNet::Server::PreFork::run_n_children('Starman::Server=HASH(0x17ec430)', 5) called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Net/Server/PreFork.pm line 111\nNet::Server::PreFork::loop('Starman::Server=HASH(0x17ec430)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Net/Server.pm line 60\nNet::Server::run('Starman::Server=HASH(0x17ec430)', 'port', 'ARRAY(0x1b386c8)', 'host', '*', 'proto', 'tcp', 'serialize', 'none', 'min_servers', 5, 'min_spare_servers', 4, 'max_spare_servers', 4, 'max_servers', 5, 'max_requests', 1000, 'user', 30220, 'group', '30220 30220 45056', 'listen', 1024, 'check_for_waiting', 1, 'no_client_stdout', 1, 'pid_file', '/disks/p3/deployment/services/Workspace/service.pid', 'setsid', 1, 'background', 1, 'log_file', '/disks/p3/deployment/services/Workspace/error.log') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Starman/Server.pm line 89\nStarman::Server::run('Starman::Server=HASH(0x17ec430)', 'CODE(0x17ec310)', 'HASH(0x17ec028)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Plack/Handler/Starman.pm line 18\nPlack::Handler::Starman::run('Plack::Handler::Starman=HASH(0x17ec3d0)', 'CODE(0x17ec310)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Plack/Loader/Delayed.pm line 20\nPlack::Loader::Delayed::run('Plack::Loader::Delayed=HASH(0x1593dd8)', 'Plack::Handler::Starman=HASH(0x17ec3d0)') called at /disks/p3/runtime/lib/perl5/site_perl/5.16.2/Plack/Runner.pm line 277\nPlack::Runner::run('Plack::Runner=HASH(0x15d9b68)') called at /disks/p3/runtime/bin/starman line 38\n"},"id":"49422058067284524"}

**Comment by sebhtml** [comment]
This is quite a long story.

This could instead be logged and just display something like "Something went wrong along the way."

**Comment by cshenry** [comment]
You know, the full trace is useful for developers. The error message. which can be trivially parsed as the text between the �ERROR_� flags is simple �Workspace not found!�. Don�t know how much simpler I can get than that.

**Comment by nconrad** [comment]
This ticket may just be outdated.  I posted the issue back when I was able to see Tom's workspace (don't remember how), but when I went to delete it, it said "Workspace not found!", which was misleading since it was right there in front of me.

**Comment by sebhtml** [comment]
I agree that it is useful for developers.
