### ISSUE TITLE
unauthorized access when downloading certain files

### ISSUE THREAD

**Issue by nconrad** [PATRIC3/Workspace#57]
Creating a ticket to keep track of this one.  I currently don't have steps to replicate the issue.  Downloading PATRIC/PATRIC Workshop/Variation/README.txt seems to work for me.

**Comment by olsonanl** [comment]
I believe this was the perms problem in get_download_url fixed in f2a55f3ac25dce45f547618b583a430c9725d0d4 and c16c7b46a11ea7bb1368983ae7f743e961b8d4eb
